"""Scene-change keyframe extractor stress test (architecture.md §3).

Feeds three synthesized 60-second mp4s generated by ffmpeg test patterns and
asserts the extractor always produces 5-8 keyframes per the spec:

  1. constant       — solid color, no motion (pure padding branch)
  2. periodic-cuts  — blend of testsrc + smptebars (chunky scene changes)
  3. fast-motion    — mandelbrot (continuously changing frames)

Skips when ffmpeg is not on PATH.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest


REPO_ROOT = Path(__file__).resolve().parents[1]
WORKER_DIR = REPO_ROOT / "apps" / "synthesis-worker"
if str(WORKER_DIR) not in sys.path:
    sys.path.insert(0, str(WORKER_DIR))


pytest.importorskip("cv2")

from keyframes import (  # noqa: E402 — sys.path-injected above
    MAX_KEYFRAMES,
    MIN_KEYFRAMES,
    extract_keyframes,
)


def _have_ffmpeg() -> bool:
    try:
        subprocess.run(["ffmpeg", "-version"], check=True, capture_output=True)
        return True
    except (FileNotFoundError, subprocess.CalledProcessError):
        return False


PATTERNS: list[tuple[str, str, list[str]]] = [
    (
        "constant",
        "color=c=navy:size=320x240:rate=1:duration=60",
        [],
    ),
    # Periodic cuts: 60s smptebars provides distinct color-band content
    # (every frame has subtle delta; cadence drives PSNR drops).
    (
        "periodic",
        "smptebars=size=320x240:rate=1:duration=60",
        [],
    ),
    # Fast motion: mandelbrot has no `duration=` arg; cap via -t instead.
    (
        "fastmotion",
        "mandelbrot=size=320x240:rate=1",
        ["-t", "60"],
    ),
]


@pytest.fixture(scope="module")
def synthesized_mp4s(tmp_path_factory) -> dict[str, Path]:
    if not _have_ffmpeg():
        pytest.skip("ffmpeg not on PATH")
    out_dir = tmp_path_factory.mktemp("kf_stress")
    mp4s: dict[str, Path] = {}
    for name, lavfi, extra in PATTERNS:
        out = out_dir / f"{name}.mp4"
        subprocess.run(
            [
                "ffmpeg", "-y",
                "-f", "lavfi", "-i", lavfi,
                *extra,
                "-c:v", "libx264", "-pix_fmt", "yuv420p",
                "-hide_banner", "-loglevel", "error",
                str(out),
            ],
            check=True,
        )
        assert out.stat().st_size > 0
        mp4s[name] = out
    return mp4s


@pytest.mark.parametrize("pattern", [name for name, _, _ in PATTERNS])
def test_extracts_5_to_8_keyframes(synthesized_mp4s, pattern: str) -> None:
    mp4 = synthesized_mp4s[pattern]
    keyframes = extract_keyframes(str(mp4))
    assert MIN_KEYFRAMES <= len(keyframes) <= MAX_KEYFRAMES, (
        f"{pattern}: expected {MIN_KEYFRAMES}-{MAX_KEYFRAMES} keyframes, got {len(keyframes)}"
    )
    # First keyframe is always frame 0 per select_scene_change_keyframes contract.
    assert keyframes[0].index == 0
    # Each keyframe must carry non-empty PNG bytes.
    for kf in keyframes:
        assert kf.png_bytes.startswith(b"\x89PNG\r\n"), f"{pattern}: bad PNG header at idx {kf.index}"
    # Timestamps monotonic.
    indices = [kf.index for kf in keyframes]
    assert indices == sorted(indices), f"{pattern}: keyframes out of order"
