#!/usr/bin/env bash
# scripts/chainguard_init.sh
#
# Bootstraps Chainguard Libraries (malware-resistant PyPI + npm mirrors) for the
# Understudy repo. Pairs with the existing Chainguard container base under
# infra/chainguard/ — together they give us supply-chain hardening at both the
# dep-install step AND the container layer.
#
# Prereqs (do these first, browser-interactive):
#   1. Create a free Chainguard account:  https://console.chainguard.dev/auth/login
#   2. Create an org (any valid-looking domain, e.g. "yourname-hackathon.dev"):
#        https://console.chainguard.dev/org/welcome/settings/organization/join
#   3. chainctl installed (brew tap chainguard-dev/tap && brew install chainctl)
#
# What this script does:
#   - chainctl auth login  (browser-interactive, one-time)
#   - Creates entitlements for PYTHON + JAVASCRIPT ecosystems
#   - Mints 30-day pull tokens for each
#   - Writes pip.conf at repo root
#   - Writes .npmrc at apps/web/ and apps/agent-template/
#   - Writes .env.chainguard (sourced by Makefile targets)
#   - Never commits the generated files — .gitignore already excludes them.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

_cyan()   { printf '\033[36m%s\033[0m\n' "$*"; }
_green()  { printf '\033[32m%s\033[0m\n' "$*"; }
_yellow() { printf '\033[33m%s\033[0m\n' "$*"; }
_red()    { printf '\033[31m%s\033[0m\n' "$*" >&2; }

require() {
  command -v "$1" >/dev/null 2>&1 || {
    _red "missing: $1"
    _red "install first: ${2:-see https://edu.chainguard.dev/chainguard/chainctl/}"
    exit 1
  }
}

require chainctl "brew tap chainguard-dev/tap && brew install chainctl"
require base64

_cyan "▸ chainctl auth login (opens browser)"
chainctl auth login

_cyan "▸ creating entitlements (idempotent; pre-existing is fine)"
chainctl libraries entitlements create --ecosystems=PYTHON || true
chainctl libraries entitlements create --ecosystems=JAVASCRIPT || true

_cyan "▸ minting pull tokens (30-day TTL)"
PY_JSON=$(chainctl auth pull-token --repository=python --ttl=720h --output=json)
JS_JSON=$(chainctl auth pull-token --repository=javascript --ttl=720h --output=json)

# Tokens have a username containing "/", which breaks basic-auth URLs for pip.
# Chainguard's workaround: substitute "/" with "_" in the URL-embedded form.
PY_USER=$(printf '%s' "$PY_JSON" | python3 -c 'import json,sys;print(json.load(sys.stdin)["username"])')
PY_PASS=$(printf '%s' "$PY_JSON" | python3 -c 'import json,sys;print(json.load(sys.stdin)["password"])')
JS_USER=$(printf '%s' "$JS_JSON" | python3 -c 'import json,sys;print(json.load(sys.stdin)["username"])')
JS_PASS=$(printf '%s' "$JS_JSON" | python3 -c 'import json,sys;print(json.load(sys.stdin)["password"])')

PY_USER_URL="${PY_USER//\//_}"
JS_AUTH_B64=$(printf '%s' "${JS_USER}:${JS_PASS}" | base64 | tr -d '\n')

_cyan "▸ writing pip.conf (repo root)"
cat > pip.conf <<EOF
# Chainguard Libraries — malware-resistant PyPI mirror.
# Generated by scripts/chainguard_init.sh. Do not commit; see .gitignore.
[global]
index-url = https://${PY_USER_URL}:${PY_PASS}@libraries.cgr.dev/python/simple
EOF

_cyan "▸ writing .npmrc for Node projects"
write_npmrc() {
  local path="$1"
  cat > "$path" <<EOF
# Chainguard Libraries — malware-resistant npm mirror.
# Generated by scripts/chainguard_init.sh. Do not commit; see .gitignore.
registry=https://libraries.cgr.dev/javascript/
//libraries.cgr.dev/javascript/:_auth=${JS_AUTH_B64}
//libraries.cgr.dev/javascript/:always-auth=true
EOF
}
write_npmrc "apps/web/.npmrc"
write_npmrc "apps/agent-template/.npmrc"

_cyan "▸ writing .env.chainguard (source this from your shell for uv/pip)"
cat > .env.chainguard <<EOF
# Source with: set -a; source .env.chainguard; set +a
# Do not commit; see .gitignore.
export UV_INDEX_URL="https://${PY_USER_URL}:${PY_PASS}@libraries.cgr.dev/python/simple"
export PIP_INDEX_URL="https://${PY_USER_URL}:${PY_PASS}@libraries.cgr.dev/python/simple"
EOF
chmod 600 .env.chainguard pip.conf apps/web/.npmrc apps/agent-template/.npmrc

_green "✓ done."
echo
_yellow "Next steps:"
echo "  python deps:  pip install --config-file pip.conf -e '.[dev]'"
echo "  web deps:     (cd apps/web && npm install)"
echo "  agent deps:   (cd apps/agent-template && npm install)"
echo "  verify npm :  curl -sI --user \"${JS_USER}:<redacted>\" https://libraries.cgr.dev/javascript/ | head -1"
echo
_yellow "Token TTL: 720h (30 days). Re-run this script to rotate."
