#!/usr/bin/env bash
# scripts/chainguard_init.sh
#
# Bootstraps Chainguard Libraries (malware-resistant PyPI + npm mirrors) for the
# Understudy repo. Pairs with the existing Chainguard container base under
# infra/chainguard/ — together they give us supply-chain hardening at both the
# dep-install step AND the container layer.
#
# Prereqs (do these first, browser-interactive):
#   1. Create a free Chainguard account:  https://console.chainguard.dev/auth/login
#   2. Create an org (any valid-looking domain, e.g. "yourname-hackathon.dev"):
#        https://console.chainguard.dev/org/welcome/settings/organization/join
#   3. chainctl installed (brew tap chainguard-dev/tap && brew install chainctl)
#
# What this script does:
#   - chainctl auth login  (browser-interactive, one-time)
#   - Creates entitlements for PYTHON + JAVASCRIPT ecosystems
#   - Mints 30-day pull tokens for each
#   - Writes pip.conf at repo root (optional local-dev shortcut for pip)
#   - Writes .env.chainguard containing PIP_INDEX_URL + NPM_CHAINGUARD_AUTH
#     → sourced by Docker builds: the Dockerfile consumes build-args from these
#       env vars so the production image resolves Python + npm packages from
#       Chainguard's rebuilt-from-source mirror.
#   - DOES NOT write a root .npmrc. Chainguard's npm mirror lags public
#     registry on fresh releases, and transitive deps with unscoped names
#     (e.g. posthog-node) have no per-package fallback. Forcing local dev
#     through it breaks routine installs. Local npm uses public registry;
#     production agent images still pull from Chainguard via the Dockerfile
#     NPM_CHAINGUARD_AUTH build-arg. Same pattern as pip.
#   - Never commits the generated files — .gitignore already excludes them.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

_cyan()   { printf '\033[36m%s\033[0m\n' "$*"; }
_green()  { printf '\033[32m%s\033[0m\n' "$*"; }
_yellow() { printf '\033[33m%s\033[0m\n' "$*"; }
_red()    { printf '\033[31m%s\033[0m\n' "$*" >&2; }

require() {
  command -v "$1" >/dev/null 2>&1 || {
    _red "missing: $1"
    _red "install first: ${2:-see https://edu.chainguard.dev/chainguard/chainctl/}"
    exit 1
  }
}

require chainctl "brew tap chainguard-dev/tap && brew install chainctl"
require base64

_cyan "▸ chainctl auth login (opens browser)"
chainctl auth login

_cyan "▸ creating entitlements (idempotent; pre-existing is fine)"
chainctl libraries entitlements create --ecosystems=PYTHON || true
chainctl libraries entitlements create --ecosystems=JAVASCRIPT || true

_cyan "▸ minting pull tokens (30-day TTL)"
PY_JSON=$(chainctl auth pull-token --repository=python --ttl=720h --output=json)
JS_JSON=$(chainctl auth pull-token --repository=javascript --ttl=720h --output=json)

# Tokens have a username containing "/", which breaks basic-auth URLs for pip.
# Chainguard's workaround: substitute "/" with "_" in the URL-embedded form.
# chainctl's --output=json emits {"identity_id": "...", "token": "..."}.
# identity_id → Basic-auth Username, token → Basic-auth Password.
PY_USER=$(printf '%s' "$PY_JSON" | python3 -c 'import json,sys;print(json.load(sys.stdin)["identity_id"])')
PY_PASS=$(printf '%s' "$PY_JSON" | python3 -c 'import json,sys;print(json.load(sys.stdin)["token"])')
JS_USER=$(printf '%s' "$JS_JSON" | python3 -c 'import json,sys;print(json.load(sys.stdin)["identity_id"])')
JS_PASS=$(printf '%s' "$JS_JSON" | python3 -c 'import json,sys;print(json.load(sys.stdin)["token"])')

PY_USER_URL="${PY_USER//\//_}"
JS_AUTH_B64=$(printf '%s' "${JS_USER}:${JS_PASS}" | base64 | tr -d '\n')

_cyan "▸ writing pip.conf (repo root)"
cat > pip.conf <<EOF
# Chainguard Libraries — malware-resistant PyPI mirror.
# Generated by scripts/chainguard_init.sh. Do not commit; see .gitignore.
[global]
index-url = https://${PY_USER_URL}:${PY_PASS}@libraries.cgr.dev/python/simple
EOF

_cyan "▸ writing .env.chainguard (Docker builds source this for build-args)"
cat > .env.chainguard <<EOF
# Source with: set -a; source .env.chainguard; set +a
# Do not commit; see .gitignore.
#
# Consumed as Dockerfile build-args:
#   Dockerfile.wolfi          →  PIP_INDEX_URL
#   Dockerfile.agent.tmpl     →  NPM_CHAINGUARD_AUTH
#
# Local shells can also use PIP_INDEX_URL directly for ad-hoc pip/uv invocations.
# Local npm intentionally NOT configured here — see scripts/chainguard_init.sh
# header for rationale (unmirrored transitive deps break workspace installs).
export UV_INDEX_URL="https://${PY_USER_URL}:${PY_PASS}@libraries.cgr.dev/python/simple"
export PIP_INDEX_URL="https://${PY_USER_URL}:${PY_PASS}@libraries.cgr.dev/python/simple"
export NPM_CHAINGUARD_AUTH="${JS_AUTH_B64}"
EOF
chmod 600 .env.chainguard pip.conf

# If a stale root .npmrc exists from an earlier run of this script, remove it
# so local npm stops routing through Chainguard's mirror.
if [[ -f .npmrc ]]; then
  _yellow "▸ removing stale root .npmrc (local npm now uses public registry; Chainguard applies in Docker build only)"
  rm -f .npmrc
fi

_green "✓ done."
echo
_yellow "Next steps:"
echo "  python deps:       pip install --config-file pip.conf -e '.[dev]'"
echo "  web deps:          npm install --workspace apps/web         # uses public npm"
echo "  agent deps:        npm install --workspace apps/agent-template  # uses public npm"
echo
echo "  Docker builds (Chainguard-verified packages end up in the shipped image):"
echo "    set -a; source .env.chainguard; set +a"
echo "    docker build --build-arg PIP_INDEX_URL \\"
echo "                 -f infra/chainguard/Dockerfile.wolfi ."
echo "    docker build --build-arg NPM_CHAINGUARD_AUTH \\"
echo "                 -f infra/chainguard/Dockerfile.agent.tmpl ."
echo
echo "  verify npm token:  curl -sI --user \"${JS_USER}:<redacted>\" https://libraries.cgr.dev/javascript/ | head -1"
echo
_yellow "Token TTL: 720h (30 days). Re-run this script to rotate."
