#!/usr/bin/env bash
# One-shot helper for wiring Chainguard Libraries (Python) into Understudy.
# Walks you through: chainctl install check → login → entitlement → pull token
# → writes pip.conf from pip.conf.example. Safe to re-run (idempotent where it can be).
#
# Runs the steps from docs/chainguard-libraries.md. Read that doc for detail.

set -euo pipefail

if [[ -t 1 ]]; then
  RED=$'\033[31m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'; BLUE=$'\033[34m'; BOLD=$'\033[1m'; RESET=$'\033[0m'
else
  RED=""; GREEN=""; YELLOW=""; BLUE=""; BOLD=""; RESET=""
fi

info()  { printf '%s[cg-setup]%s %s\n' "$BLUE"   "$RESET" "$*"; }
ok()    { printf '%s[cg-setup]%s %s\n' "$GREEN"  "$RESET" "$*"; }
warn()  { printf '%s[cg-setup]%s %s\n' "$YELLOW" "$RESET" "$*" >&2; }
die()   { printf '%s[cg-setup]%s %s\n' "$RED"    "$RESET" "$*" >&2; exit 1; }

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

info "Running in $ROOT"

# --- 1. chainctl ------------------------------------------------------------
if ! command -v chainctl >/dev/null 2>&1; then
  cat <<EOF

${BOLD}chainctl is not installed.${RESET}

Install (pick one):
  brew tap chainguard-dev/tap && brew install chainctl
  # or:
  curl -o chainctl "https://dl.enforce.dev/chainctl/latest/chainctl_\$(uname -s | tr '[:upper:]' '[:lower:]')_\$(uname -m | sed 's/aarch64/arm64/')"
  sudo install -m 0755 chainctl /usr/local/bin/chainctl

Then re-run this script.
EOF
  exit 1
fi
ok "chainctl found: $(chainctl version 2>&1 | head -n1)"

# --- 2. login ---------------------------------------------------------------
if ! chainctl auth status >/dev/null 2>&1; then
  info "Not logged in. Opening browser for chainctl auth login..."
  chainctl auth login
else
  ok "chainctl session active"
fi

# --- 3. Python entitlement --------------------------------------------------
info "Ensuring PYTHON ecosystem entitlement exists..."
if chainctl libraries entitlements create --ecosystems=PYTHON 2>&1 | tee /tmp/cg-ent.log | grep -qi "already exists"; then
  ok "PYTHON entitlement already active"
else
  ok "PYTHON entitlement created"
fi

# --- 4. Pull token ----------------------------------------------------------
info "Generating a pull token (30-day TTL)..."
token_output="$(chainctl auth pull-token --repository=python --ttl=720h 2>&1)"
echo "$token_output"

username="$(grep -E '^Username' <<<"$token_output" | awk -F': *' '{print $2}')"
password="$(grep -E '^Password' <<<"$token_output" | awk -F': *' '{print $2}')"

if [[ -z "$username" || -z "$password" ]]; then
  die "Couldn't parse Username/Password from chainctl output. Copy them manually and fill pip.conf from pip.conf.example."
fi

# URL-encode the '/' in the username to '_'. Chainguard libraries.cgr.dev
# returns 403 otherwise.
username_urlsafe="${username//\//_}"

# --- 5. Write pip.conf ------------------------------------------------------
if [[ -f pip.conf ]]; then
  warn "pip.conf already exists — moving to pip.conf.bak"
  mv pip.conf pip.conf.bak
fi

cat >pip.conf <<EOF
# Auto-generated by scripts/setup_chainguard_libraries.sh
# Token TTL: 30 days from creation. See docs/chainguard-libraries.md for rotation.
[global]
index-url = https://${username_urlsafe}:${password}@libraries.cgr.dev/python/simple
extra-index-url = https://pypi.org/simple
EOF
chmod 600 pip.conf
ok "Wrote pip.conf (chmod 600) — .gitignored, never committed"

# --- 6. Print build-arg string ---------------------------------------------
cat <<EOF

${BOLD}Docker build invocation for Chainguard Libraries:${RESET}

  URL="https://${username_urlsafe}:${password}@libraries.cgr.dev/python/simple"

  docker build \\
    --build-arg PIP_INDEX_URL="\${URL}" \\
    --build-arg PIP_EXTRA_INDEX_URL="https://pypi.org/simple" \\
    -f infra/chainguard/Dockerfile.wolfi \\
    -t understudy-agent-base:cg-libs .

${BOLD}GitHub Actions secrets to set:${RESET}
  CHAINGUARD_PYTHON_USERNAME = ${username_urlsafe}
  CHAINGUARD_PYTHON_PASSWORD = <password from above>

Patch instructions: docs/chainguard-libraries.md → "CI — GitHub Actions".

EOF

ok "Setup complete."
